baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

baseurl = "https://[yourgithubname].github.io" 
#設定主頁 url
 
languageCode = "zh-tw" 
#設定 Blog 語言
 
title = "Whatever you want" 
#設定網站標題
 
buildDrafts = false 
#是否產生草稿(建議選否)